### ISSUE TITLE
login unsuccessful

### ISSUE THREAD

**Issue by tom0034** [bengood362/cuhk_blackboard_crawler#3]
![image](https://user-images.githubusercontent.com/11575182/48623401-7e904700-e9e4-11e8-8353-d66df7905438.png)

**Comment by bengood362** [comment]
What courses do you have?
tried to fix it in c3e84a95ce8a8b1711809662e08b70f2c40fd107, see if it works now?

**Comment by tom0034** [comment]
![image](https://user-images.githubusercontent.com/11575182/48634942-c1ace300-ea01-11e8-8d15-19c782904958.png)
Still not working

**Comment by bengood362** [comment]
The problem should be fixed in latest commit 7f211a3152885bd4bc9a63ea567f847e8f31ea98
Please pull and try again. 
Please reply if the problem persists.

if it is still not working, temporary fix is change main:184-193 into `def log(self, s, t=0, coding='utf-8'): pass`, and BlackboardCrawler.py:104-112 into `def log(self, s,t=0, coding='utf-8'): pass`

**Comment by bengood362** [comment]
I have attempt to fix it againnnnnn
https://github.com/bengood362/cuhk_blackboard_crawler/tree/encoding_test
please try and tell me the result, thanks!

**Comment by tom0034** [comment]
Problem fixed, thank you for your great effort!
